export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as Stats } from './Stats';
export { default as AboutSection } from './AboutSection';
export { default as MosqueSection } from './MosqueSection';
export { default as ProjectsSection } from './ProjectsSection';
export { default as DonationSection } from './DonationSection';
export { default as ContactSection } from './ContactSection';
export { default as Footer } from './Footer';
